Furnitures = {
    {
        categoryName = "Doors",
        items = {
            { name = "v_ilev_gc_door02", price = 50, isDoor = true, label = "White Door" }, -- requires isDoor = true if its a door to behave like a door
        }
    },
    {
		categoryName = 'Sofas',
		items = {
			{ name = 'miss_rub_couch_01', price = 50, label = 'Old couch' },
			{ name = 'prop_fib_3b_bench', price = 50, label = 'Threesits couch' },
			{ name = 'prop_ld_farm_chair01', price = 50, label = 'Old chair' },
			{ name = 'prop_ld_farm_couch01', price = 50, label = 'Old treesits couch' },
			{ name = 'prop_ld_farm_couch02', price = 50, label = 'Old striped couch' },
			{ name = 'v_res_d_armchair', price = 50, label = 'Old 1 Seat Couch Yellow' },
			{ name = 'v_res_fh_sofa', price = 50, label = 'corner sofa' },
			{ name = 'v_res_mp_sofa', price = 50, label = 'corner sofa 2' },
			{ name = 'v_res_d_sofa', price = 50, label = 'couch 1' },
			{ name = 'v_res_j_sofa', price = 50, label = 'Couch 2' },
			{ name = 'v_res_mp_stripchair', price = 50, label = 'Couch 3' },
			{ name = 'v_res_m_h_sofa_sml', price = 50, label = 'Couch 4' },
			{ name = 'v_res_r_sofa', price = 50, label = 'Couch 5' },
			{ name = 'v_res_tre_sofa', price = 50, label = 'Couch 6' },
			{ name = 'v_res_tre_sofa_mess_a', price = 50, label = 'Couch 7' },
			{ name = 'v_res_tre_sofa_mess_b', price = 50, label = 'Couch 8' },
			{ name = 'v_res_tre_sofa_mess_c', price = 50, label = 'Couch 9' },
			{ name = 'v_res_tt_sofa', price = 50, label = 'Couch 10' },
			{ name = 'prop_rub_couch02', price = 50, label = 'Couch 11' },
			{ name = 'v_ilev_m_sofa', price = 50, label = 'White Couch' },
			{ name = 'v_med_p_sofa', price = 50, label = 'Lether Couch Brown' },
			{ name = 'v_club_officesofa', price = 50, label = 'pauper Couch rood' },
			{ name = 'bkr_prop_clubhouse_sofa_01a', price = 50, label = 'Black Couch' },
			{ name = 'apa_mp_h_stn_sofacorn_01', price = 50, label = 'corner sofa 3' },
			{ name = 'prop_couch_lg_02', price = 50, label = 'Couch hout' },
			{ name = 'apa_mp_h_stn_sofacorn_10', price = 50, label = 'corner sofa 4' },
			{ name = 'apa_mp_h_yacht_sofa_02', price = 50, label = 'Brown Couch' },
			{ name = 'apa_mp_h_yacht_sofa_01', price = 50, label = 'White long Couch' },
			{ name = 'prop_couch_01', price = 50, label = 'sofa cushions' },
			{ name = 'prop_couch_03', price = 50, label = 'sofa yellow' },
			{ name = 'prop_couch_04', price = 50, label = 'leather sofa cushions' },
			{ name = 'prop_couch_lg_05', price = 50, label = 'sofa corduroy' },
			{ name = 'prop_couch_lg_06', price = 50, label = 'leather sofa brown 2' },
			{ name = 'prop_couch_lg_07', price = 50, label = 'sofa cushions 2' },
			{ name = 'prop_couch_lg_08', price = 50, label = 'leather sofa brown 3' },
			{ name = 'prop_couch_sm1_07', price = 50, label = 'leather sofa corner' },
			{ name = 'prop_couch_sm2_07', price = 50, label = 'leather sofa straight' },
			{ name = 'prop_couch_sm_06', price = 50, label = 'leather sofa small' },
			{ name = 'apa_mp_h_stn_sofa2seat_02', price = 50, label = 'love seat' },
			{ name = 'apa_mp_h_stn_sofacorn_05', price = 50, label = 'corner sofa 5' },
			{ name = 'apa_mp_h_stn_sofacorn_06', price = 50, label = 'corner sofa 6' },
			{ name = 'apa_mp_h_stn_sofacorn_07', price = 50, label = 'corner sofa 7' },
			{ name = 'apa_mp_h_stn_sofacorn_08', price = 50, label = 'corner sofa 8' },
			{ name = 'apa_mp_h_stn_sofacorn_09', price = 50, label = 'corner sofa 9' },
			{ name = 'ex_mp_h_off_sofa_003', price = 50, label = 'sofa blue fabric' },
			{ name = 'ex_mp_h_off_sofa_01', price = 50, label = 'sofa white leather' },
			{ name = 'ex_mp_h_off_sofa_02', price = 50, label = 'sofa black leather' },
			{ name = 'hei_heist_stn_sofa2seat_03', price = 50, label = 'sofa modern' },
			{ name = 'hei_heist_stn_sofa2seat_06', price = 50, label = 'couch brown' },
			{ name = 'hei_heist_stn_sofa3seat_01', price = 50, label = 'chaise lounge' },
			{ name = 'hei_heist_stn_sofa3seat_02', price = 50, label = 'sofa modern 2' },
			{ name = 'hei_heist_stn_sofa3seat_06', price = 50, label = 'sofa modern 3' },
			{ name = 'imp_prop_impexp_sofabed_01a', price = 50, label = 'sofa bed' },
			{ name = 'prop_t_sofa_02', price = 50, label = 'sofa bed2' }
		},
	},
	{
		categoryName = "Chair's",
		items = {
			{ name = 'v_res_d_highchair', price = 50, label = 'High chair' },
			{ name = 'apa_mp_h_stn_chairstrip_03', price = 50, label = 'Sitchair 4' },
			{ name = 'v_res_fa_chair01', price = 50, label = 'Chairl' },
			{ name = 'v_res_fa_chair02', price = 50, label = 'Chair 2' },
			{ name = 'v_res_fh_barcchair', price = 50, label = 'High chair 2' },
			{ name = 'v_res_fh_dineeamesa', price = 50, label = 'Kitchen chair 1' },
			{ name = 'v_res_fh_dineeamesb', price = 50, label = 'Kitchen chair 2' },
			{ name = 'v_res_fh_dineeamesc', price = 50, label = 'Kitchen chair 3' },
			{ name = 'v_res_fh_easychair', price = 50, label = 'Chair 3' },
			{ name = 'v_res_fh_kitnstool', price = 50, label = 'Chair 4' },
			{ name = 'v_res_fh_singleseat', price = 50, label = 'High chair 3' },
			{ name = 'v_res_jarmchair', price = 50, label = 'Arm Chair' },
			{ name = 'v_res_j_dinechair', price = 50, label = 'Kitchen chair 4' },
			{ name = 'v_res_j_stool', price = 50, label = 'Chair 5' },
			{ name = 'v_res_mbchair', price = 50, label = 'MB Chair' },
			{ name = 'v_res_m_armchair', price = 50, label = 'Arm Chair 2' },
			{ name = 'v_res_m_dinechair', price = 50, label = 'Kitchen chair 5' },
			{ name = 'v_res_study_chair', price = 50, label = 'Study Chair' },
			{ name = 'v_res_trev_framechair', price = 50, label = 'Chair frame' },
			{ name = 'v_res_tre_chair', price = 50, label = 'Chair 5' },
			{ name = 'v_res_tre_officechair', price = 50, label = 'officeChair' },
			{ name = 'v_res_tre_stool', price = 50, label = 'Chair 6' },
			{ name = 'v_res_tre_stool_leather', price = 50, label = 'Lether Chair' },
			{ name = 'v_res_tre_stool_scuz', price = 50, label = 'Chair Scuz' },
			{ name = 'v_med_p_deskchair', price = 50, label = 'DeskChair' },
			{ name = 'v_med_p_easychair', price = 50, label = 'Easy Chair' },
			{ name = 'v_med_whickerchair1', price = 50, label = 'Whicker Chair' },
			{ name = 'prop_direct_chair_01', price = 50, label = 'Direct Chair' },
			{ name = 'prop_direct_chair_02', price = 50, label = 'Direct Chair 2' },
			{ name = 'prop_yacht_lounger', price = 50, label = 'Yacht Chair 1' },
			{ name = 'prop_yacht_seat_01', price = 50, label = 'Yacht Chair 2' },
			{ name = 'prop_yacht_seat_02', price = 50, label = 'Yacht Chair 3' },
			{ name = 'prop_yacht_seat_03', price = 50, label = 'Yacht Chair 4' },
			{ name = 'v_ret_chair_white', price = 50, label = 'White Chair' },
			{ name = 'v_ret_chair', price = 50, label = 'Chair 7' },
			{ name = 'v_ret_ta_stool', price = 50, label = 'TA Chair' },
			{ name = 'prop_cs_office_chair', price = 50, label = 'office Chair 2' },
			{ name = 'apa_mp_h_yacht_armchair_01', price = 50, label = 'White fauteuil' },
			{ name = 'v_club_barchair', price = 50, label = 'Chair 8' },
			{ name = 'prop_off_chair_04', price = 50, label = 'Desk Chair 2' },
			{ name = 'v_club_stagechair', price = 50, label = 'fauteuil roze' },
			{ name = 'v_club_officechair', price = 50, label = 'Desk Chair 3' },
			{ name = 'prop_armchair_01', price = 50, label = 'Sit chair' },
			{ name = 'prop_bar_stool_01', price = 50, label = 'Barstool' },
			{ name = 'apa_mp_h_yacht_stool_01', price = 50, label = 'White pouffe' },
			{ name = 'apa_mp_h_stn_chairarm_12', price = 50, label = 'Sitchair 3' },
			{ name = 'apa_mp_h_stn_chairstool_12', price = 50, label = 'Feet support' },
			{ name = 'prop_chair_03', price = 50, label = 'Wooden Chair' },
			{ name = 'prop_couch_sm_05', price = 50, label = 'corduroy armchair' },
			{ name = 'prop_couch_sm_07', price = 50, label = 'white armchair 2' },
			{ name = 'prop_couch_sm_02', price = 50, label = 'orange armchair' },
			{ name = 'apa_mp_h_stn_sofa_daybed_01', price = 50, label = 'lounge chair' },
			{ name = 'apa_mp_h_stn_sofa_daybed_02', price = 50, label = 'lounge chair 2' },
			{ name = 'apa_mp_h_din_chair_04', price = 50, label = 'modern chair' },
			{ name = 'apa_mp_h_din_chair_08', price = 50, label = 'modern chair 2' },
			{ name = 'apa_mp_h_din_chair_09', price = 50, label = 'modern chair 3' },
			{ name = 'apa_mp_h_din_chair_12', price = 50, label = 'modern chair 4' },
			{ name = 'apa_mp_h_din_stool_04', price = 50, label = 'modern chair 5' },
			{ name = 'apa_mp_h_stn_chairarm_01', price = 50, label = 'modern chair 6' },
			{ name = 'apa_mp_h_stn_chairarm_02', price = 50, label = 'modern chair 7' },
			{ name = 'apa_mp_h_stn_chairarm_03', price = 50, label = 'modern chair 8' },
			{ name = 'apa_mp_h_stn_chairarm_09', price = 50, label = 'modern chair 9' },
			{ name = 'apa_mp_h_stn_chairarm_11', price = 50, label = 'modern chair 10' },
			{ name = 'apa_mp_h_stn_chairarm_13', price = 50, label = 'modern chair 11' },
			{ name = 'apa_mp_h_stn_chairarm_24', price = 50, label = 'modern chair 12' },
			{ name = 'apa_mp_h_stn_chairarm_25', price = 50, label = 'modern chair 13' },
			{ name = 'apa_mp_h_stn_chairarm_26', price = 50, label = 'modern chair 14' },
			{ name = 'apa_mp_h_stn_chairstrip_04', price = 50, label = 'modern chair 15' },
			{ name = 'apa_mp_h_stn_chairstrip_05', price = 50, label = 'modern chair 16' },
			{ name = 'apa_mp_h_stn_chairstrip_08', price = 50, label = 'modern chair 17' },
			{ name = 'apa_mp_h_stn_foot_stool_01', price = 50, label = 'pouffe' },
			{ name = 'apa_mp_h_stn_foot_stool_02', price = 50, label = 'pouffe 2' },
			{ name = 'apa_mp_h_yacht_barstool_01', price = 50, label = 'barstool 2' },
			{ name = 'ba_prop_int_glam_stool', price = 50, label = 'barstool 3' },
			{ name = 'ba_prop_battle_club_chair_01', price = 50, label = 'office chair' },
			{ name = 'ba_prop_battle_club_chair_02', price = 50, label = 'office chair 2' },
			{ name = 'ba_prop_battle_club_chair_03', price = 50, label = 'office chair 3' },
			{ name = 'ba_prop_battle_control_seat', price = 50, label = 'gaming chair' }
		},
	},
	{
		categoryName = 'Beds',
		items = {
			{ name = 'v_res_d_bed', price = 50, label = 'Bed 1' },
			{ name = 'v_res_lestersbed', price = 50, label = 'Bed 2' },
			{ name = 'v_res_mbbed', price = 50, label = 'MB Bed' },
			{ name = 'v_res_mdbed', price = 50, label = 'MD Bed' },
			{ name = 'v_res_msonbed', price = 50, label = 'Bed 3' },
			{ name = 'v_res_tre_bed1', price = 50, label = 'Bed 4' },
			{ name = 'v_res_tre_bed2', price = 50, label = 'T Bed' },
			{ name = 'v_res_tt_bed', price = 50, label = 'TT Bed' },
			{ name = 'apa_mp_h_bed_with_table_02', price = 50, label = 'fancy bed' },
			{ name = 'apa_mp_h_bed_wide_05', price = 50, label = 'red bed' },
			{ name = 'apa_mp_h_bed_double_08', price = 50, label = 'square bed' },
			{ name = 'apa_mp_h_bed_double_09', price = 50, label = 'modern bed' },
			{ name = 'apa_mp_h_yacht_bed_01', price = 50, label = 'california king' },
			{ name = 'apa_mp_h_yacht_bed_02', price = 50, label = 'california king 2' },
			{ name = 'bkr_prop_biker_campbed_01', price = 50, label = 'camp bed' },
			{ name = 'ex_prop_exec_bed_01', price = 50, label = 'small bed' },
			{ name = 'gr_prop_bunker_bed_01', price = 50, label = 'klein bed 2' },
			{ name = 'p_mbbed_s', price = 50, label = 'Bed 5' }
		},
	},
	{
		categoryName = 'General',
		items = {
			{ name = 'v_corp_facebeanbag', price = 50, label = 'Bean Bag 1' },
			{ name = 'v_res_cherubvase', price = 50, label = 'White Vase' },
			{ name = 'v_res_d_paddedwall', price = 50, label = 'Padded Wall' },
			{ name = 'v_res_d_ramskull', price = 50, label = 'Item' },
			{ name = 'v_res_d_whips', price = 50, label = 'Whips' },
			{ name = 'v_res_fashmag1', price = 50, label = 'Mags' },
			{ name = 'v_res_fashmagopen', price = 50, label = 'Mags Open' },
			{ name = 'v_res_fa_magtidy', price = 50, label = 'Mag Tidy' },
			{ name = 'v_res_fa_yogamat002', price = 50, label = 'Yoga Mat 1' },
			{ name = 'v_res_fa_yogamat1', price = 50, label = 'Yoga Mat 2' },
			{ name = 'v_res_fh_aftershavebox', price = 50, label = 'Aftershave' },
			{ name = 'v_res_fh_flowersa', price = 50, label = 'Flowers' },
			{ name = 'v_res_fh_fruitbowl', price = 50, label = 'Fruitbowl' },
			{ name = 'v_res_fh_laundrybasket', price = 50, label = 'Laundry Basket' },
			{ name = 'v_res_fh_pouf', price = 50, label = 'Pouf' },
			{ name = 'v_res_fh_sculptmod', price = 50, label = 'Sculpture' },
			{ name = 'v_res_j_magrack', price = 50, label = 'Mag Rack' },
			{ name = 'v_res_jewelbox', price = 50, label = 'Jewel Box' },
			{ name = 'v_res_mbbin', price = 50, label = 'Bin' },
			{ name = 'v_res_mbowlornate', price = 50, label = 'Ornate Bowl' },
			{ name = 'v_res_mbronzvase', price = 50, label = 'Bronze Vase' },
			{ name = 'v_res_mchalkbrd', price = 50, label = 'Chalk Board' },
			{ name = 'v_res_mddresser', price = 50, label = 'Dresser' },
			{ name = 'v_res_mplinth', price = 50, label = 'Linth' },
			{ name = 'v_res_mp_ashtrayb', price = 50, label = 'Ashtray' },
			{ name = 'v_res_m_candle', price = 50, label = 'Candle' },
			{ name = 'v_res_m_candlelrg', price = 50, label = 'Candle Large' },
			{ name = 'v_res_m_kscales', price = 50, label = 'Scales' },
			{ name = 'v_res_tt_bedpillow', price = 50, label = 'Bed Pillow' },
			{ name = 'v_med_cor_whiteboard', price = 50, label = 'whiteboard' },
			{ name = 'prop_ashtray_01', price = 50, label = 'asbak black' },
			{ name = 'v_ret_fh_ashtray', price = 50, label = 'asbak stone' },
			{ name = 'v_24_wdr_mesh_rugs', price = 50, label = 'Rag' },
			{ name = 'apa_mp_h_acc_rugwooll_04', price = 50, label = 'Rug 2' },
			{ name = 'ex_mp_h_acc_rugwoolm_04', price = 50, label = 'Rug 3' },
			{ name = 'apa_mp_h_acc_rugwoolm_03', price = 50, label = 'Rug 4' },
			{ name = 'apa_mp_h_acc_rugwooll_03', price = 50, label = 'Rug 5' },
			{ name = 'apa_mp_h_acc_rugwoolm_04', price = 50, label = 'Rug 6' },
			{ name = 'v_club_rack', price = 50, label = 'kledingrek' }
		},
	},
	{
		categoryName = 'Props',
		items = {
			{ name = 'prop_a4_pile_01', price = 50, label = 'A4 Pile' },
			{ name = 'prop_amb_40oz_03', price = 50, label = '40 oz' },
			{ name = 'prop_amb_beer_bottle', price = 50, label = 'Beer' },
			{ name = 'prop_aviators_01', price = 50, label = 'Aviators' },
			{ name = 'prop_barry_table_detail', price = 50, label = 'Detail' },
			{ name = 'prop_beer_box_01', price = 50, label = 'Beers' },
			{ name = 'prop_binoc_01', price = 50, label = 'Binoculars' },
			{ name = 'prop_blox_spray', price = 50, label = 'Blox Spray' },
			{ name = 'prop_bongos_01', price = 50, label = 'Bongos' },
			{ name = 'prop_bong_01', price = 50, label = 'Bong' },
			{ name = 'prop_boombox_01', price = 50, label = 'Boombox' },
			{ name = 'prop_bowl_crisps', price = 50, label = 'Bowl Crisps' },
			{ name = 'prop_candy_pqs', price = 50, label = 'Candy' },
			{ name = 'prop_carrier_bag_01', price = 50, label = 'Carrier bag' },
			{ name = 'prop_ceramic_jug_01', price = 50, label = 'Ceramic Jug' },
			{ name = 'prop_cigar_pack_01', price = 50, label = 'Cigar Pack 1' },
			{ name = 'prop_cigar_pack_02', price = 50, label = 'Cigar Pack 2' },
			{ name = 'prop_cs_beer_box', price = 50, label = 'Beer Box 2' },
			{ name = 'prop_cs_binder_01', price = 50, label = 'Binder' },
			{ name = 'prop_cs_bs_cup', price = 50, label = 'Cup' },
			{ name = 'prop_cs_cashenvelope', price = 50, label = 'Envelope' },
			{ name = 'prop_cs_champ_flute', price = 50, label = 'Flute' },
			{ name = 'prop_cs_duffel_01', price = 50, label = 'Duffel Bag' },
			{ name = 'prop_cs_dvd', price = 50, label = 'DVD' },
			{ name = 'prop_cs_dvd_case', price = 50, label = 'DVD Case' },
			{ name = 'prop_cs_film_reel_01', price = 50, label = 'Film Reel' },
			{ name = 'prop_cs_ilev_blind_01', price = 50, label = 'Blind' },
			{ name = 'p_ld_bs_bag_01', price = 50, label = 'Bag' },
			{ name = 'prop_cs_ironing_board', price = 50, label = 'Ironing Board' },
			{ name = 'prop_cs_katana_01', price = 50, label = 'Katana' },
			{ name = 'prop_cs_kettle_01', price = 50, label = 'Kettle' },
			{ name = 'prop_cs_lester_crate', price = 50, label = 'Crate' },
			{ name = 'prop_cs_petrol_can', price = 50, label = 'Petrol Can' },
			{ name = 'prop_cs_sack_01', price = 50, label = 'Sack' },
			{ name = 'prop_cs_script_bottle_01', price = 50, label = 'Script Bottle' },
			{ name = 'prop_cs_script_bottle', price = 50, label = 'Script Bottle 2' },
			{ name = 'prop_cs_street_binbag_01', price = 50, label = 'Bin Bag' },
			{ name = 'prop_cs_whiskey_bottle', price = 50, label = 'Whiskey Bottle' },
			{ name = 'prop_sh_bong_01', price = 50, label = 'Bong' },
			{ name = 'prop_peanut_bowl_01', price = 50, label = 'Peanuts' },
			{ name = 'prop_tumbler_01', price = 50, label = 'Tumbler' },
			{ name = 'prop_weed_bottle', price = 50, label = 'Weed koker' },
			{ name = 'p_cs_lighter_01', price = 50, label = 'Lighter' },
			{ name = 'p_cs_papers_01', price = 50, label = 'Rolling papers' },
			{ name = 'v_res_d_dildo_f', price = 50, label = 'dildo Black' },
			{ name = 'v_res_d_dildo_c', price = 50, label = 'dildo white' },
			{ name = 'v_res_d_dildo_a', price = 50, label = "Mommy's toy" },
			{ name = 'prop_champ_cool', price = 50, label = 'Champagne cooler' },
			{ name = 'prop_champ_01b', price = 50, label = 'champagnebottle' },
			{ name = 'prop_champ_flute', price = 50, label = 'champagneglas' },
			{ name = 'ba_prop_club_champset', price = 50, label = 'champagneset' },
			{ name = 'v_res_fa_candle01', price = 50, label = 'candle blue' },
			{ name = 'v_res_fa_candle02', price = 50, label = 'candle red' },
			{ name = 'v_res_fa_candle03', price = 50, label = 'candle black' },
			{ name = 'v_res_fa_candle04', price = 50, label = 'candle small' },
			{ name = 'v_med_bottles2', price = 50, label = 'Chemicals' },
			{ name = 'v_res_desktidy', price = 50, label = 'Office stuf' },
			{ name = 'v_med_p_notebook', price = 50, label = "Note's" },
			{ name = 'bkr_prop_weed_dry_01a', price = 50, label = 'mountain of weed' },
			{ name = 'ba_prop_battle_trophy_battler', price = 50, label = 'fist trofee' },
			{ name = 'ba_prop_battle_trophy_no1', price = 50, label = 'ster trofee' },
			{ name = 'prop_golf_bag_01c', price = 50, label = 'Golf bag' },
			{ name = 'hei_heist_kit_bin_01', price = 50, label = 'Garbage can' },
			{ name = 'prop_wooden_barrel', price = 50, label = 'wooden vat' },
			{ name = 'bkr_prop_bkr_cash_scatter_01', price = 50, label = 'scatter' },
			{ name = 'bkr_prop_bkr_cashpile_01', price = 50, label = 'Cash' },
			{ name = 'bkr_prop_bkr_cash_roll_01', price = 50, label = 'Cash roll' },
			{ name = 'bkr_prop_bkr_cashpile_04', price = 50, label = 'pile of cash' },
			{ name = 'bkr_prop_weed_bigbag_open_01a', price = 50, label = 'Weed open bag' },
			{ name = 'bkr_prop_weed_bigbag_02a', price = 50, label = 'Weed bag 2' },
			{ name = 'bkr_prop_weed_bigbag_03a', price = 50, label = 'Weed bag 3' },
			{ name = 'bkr_prop_weed_scales_01a', price = 50, label = 'scales' },
			{ name = 'bkr_prop_weed_smallbag_01a', price = 50, label = 'small bag' },
			{ name = 'prop_gold_bar', price = 50, label = 'Gold Bar' },
			{ name = 'beerrow_world', price = 50, label = 'beer bottles' },
			{ name = 'beerrow_local', price = 50, label = 'beer bottles 2' },
			{ name = 'p_cs_bbbat_01', price = 50, label = 'Bat' },
			{ name = 'p_cs_cuffs_02_s', price = 50, label = 'handcuffs' },
			{ name = 'p_cs_joint_02', price = 50, label = 'Joint' },
			{ name = 'p_ing_coffeecup_01', price = 50, label = 'Coffee mug' },
			{ name = 'p_tumbler_cs2_s', price = 50, label = 'Tumbler' },
			{ name = 'prop_turkey_leg_01', price = 50, label = 'chicken leg' },
			{ name = 'prop_amb_donut', price = 50, label = 'Donut' },
			{ name = 'prop_donut_02', price = 50, label = 'Donut 2' },
			{ name = 'prop_bar_shots', price = 50, label = 'Bar shots' },
			{ name = 'prop_bar_stirrers', price = 50, label = 'Bar stirrers' },
			{ name = 'prop_beer_amopen', price = 50, label = 'Beer open' },
			{ name = 'prop_beer_blr', price = 50, label = 'Beer 1' },
			{ name = 'prop_beer_logger', price = 50, label = 'Beer 2' },
			{ name = 'prop_beer_stzopen', price = 50, label = 'Beer 3' },
			{ name = 'prop_bikerset', price = 50, label = 'Biker Set' },
			{ name = 'prop_bottle_brandy', price = 50, label = 'Bottle brandy' },
			{ name = 'prop_tequila_bottle', price = 50, label = 'Tequila bottle' },
			{ name = 'prop_tequila', price = 50, label = 'Tequila' },
			{ name = 'prop_bottle_cognac', price = 50, label = 'Bottle of Cognac' },
			{ name = 'prop_bottle_macbeth', price = 50, label = 'Bottle of Macbeth' },
			{ name = 'prop_brandy_glass', price = 50, label = 'Brandy Glass' },
			{ name = 'prop_mug_01', price = 50, label = 'Mug 1' },
			{ name = 'prop_mug_02', price = 50, label = 'Mug 2' },
			{ name = 'prop_mug_03', price = 50, label = 'Mug 3' },
			{ name = 'prop_optic_vodka', price = 50, label = 'Vodka' },
			{ name = 'prop_optic_jd', price = 50, label = 'JD' },
			{ name = 'prop_pint_glass_01', price = 50, label = 'Pint Glass' },
			{ name = 'prop_pizza_box_03', price = 50, label = 'Pizza box' },
			{ name = 'prop_sandwich_01', price = 50, label = 'Sandwich' },
			{ name = 'prop_cava', price = 50, label = 'Cava' },
			{ name = 'prop_drink_redwine', price = 50, label = 'Red wine' },
			{ name = 'vodkarow', price = 50, label = 'Vodka Row' },
			{ name = 'prop_cherenkov_02', price = 50, label = 'Cherenkov' },
			{ name = 'prop_cherenkov_03', price = 50, label = 'Cherenkov 2' },
			{ name = 'prop_cocktail_glass', price = 50, label = 'Cocktail glass' },
			{ name = 'prop_cs_bottle_opener', price = 50, label = 'Fles opener' },
			{ name = 'prop_food_bs_chips', price = 50, label = 'Chips' },
			{ name = 'prop_cs_burger_01', price = 50, label = 'Burger' },
			{ name = 'prop_cs_hand_radio', price = 50, label = 'Hand radio' },
			{ name = 'prop_cs_hotdog_01', price = 50, label = 'Hotdog' },
			{ name = 'prop_cs_milk_01', price = 50, label = 'Milk' },
			{ name = 'prop_cs_panties', price = 50, label = 'Panties' },
			{ name = 'prop_cs_steak', price = 50, label = 'Meat' }
		},
	},
	{
		categoryName = 'Random',
		items = {
			{ name = 'v_ret_csr_bin', price = 50, label = 'CSR Bin' },
			{ name = 'v_ret_fh_wickbskt', price = 50, label = 'Basket' },
			{ name = 'v_ret_gc_bag01', price = 50, label = 'GC Bag 1' },
			{ name = 'v_ret_gc_bag02', price = 50, label = 'GC Bag 2' },
			{ name = 'v_ret_gc_bin', price = 50, label = 'GC Bin' },
			{ name = 'v_ret_gc_cashreg', price = 50, label = 'Cash Register' },
			{ name = 'v_ret_gc_chair01', price = 50, label = 'GC Chair 01' },
			{ name = 'v_ret_gc_chair02', price = 50, label = 'GC Chair 02' },
			{ name = 'v_ret_gc_clock', price = 50, label = 'Clock' },
			{ name = 'v_ret_hd_prod1_', price = 50, label = 'Prod 1' },
			{ name = 'v_ret_hd_prod2_', price = 50, label = 'Prod 2' },
			{ name = 'v_ret_hd_prod3_', price = 50, label = 'Prod 3' },
			{ name = 'v_ret_hd_prod4_', price = 50, label = 'Prod 4' },
			{ name = 'v_ret_hd_prod5_', price = 50, label = 'Prod 5' },
			{ name = 'v_ret_hd_prod6_', price = 50, label = 'Prod 6' },
			{ name = 'v_ret_hd_unit1_', price = 50, label = 'HD Unit 1' },
			{ name = 'v_ret_hd_unit2_', price = 50, label = 'HD Unit 2' },
			{ name = 'v_ret_ml_fridge02', price = 50, label = 'Fridge' },
			{ name = 'v_ret_ps_bag_01', price = 50, label = 'Bag 1' },
			{ name = 'v_ret_ps_bag_02', price = 50, label = 'Bag 2' },
			{ name = 'v_ret_ta_book1', price = 50, label = 'Book 1' },
			{ name = 'v_ret_ta_book2', price = 50, label = 'Book 2' },
			{ name = 'v_ret_ta_book3', price = 50, label = 'Book 3' },
			{ name = 'v_ret_ta_book4', price = 50, label = 'Book 4' },
			{ name = 'v_ret_ta_camera', price = 50, label = 'Cam' },
			{ name = 'v_ret_ta_firstaid', price = 50, label = 'First Aid' },
			{ name = 'v_ret_ta_hero', price = 50, label = 'Hero' },
			{ name = 'v_ret_ta_mag1', price = 50, label = 'Mag 1' },
			{ name = 'v_ret_ta_mag2', price = 50, label = 'Mag 2' },
			{ name = 'v_ret_ta_skull', price = 50, label = 'Skull' },
			{ name = 'prop_acc_guitar_01', price = 50, label = 'Guitar' },
			{ name = 'prop_amb_handbag_01', price = 50, label = 'Handbag' },
			{ name = 'prop_attache_case_01', price = 50, label = 'Case' },
			{ name = 'prop_big_bag_01', price = 50, label = 'Big Bag' },
			{ name = 'prop_bonesaw', price = 50, label = 'Bonesaw' },
			{ name = 'prop_cs_fertilizer', price = 50, label = 'Fertilizer' },
			{ name = 'prop_cs_shopping_bag', price = 50, label = 'Shopping Bag' },
			{ name = 'prop_cs_vial_01', price = 50, label = 'Vial' },
			{ name = 'prop_defilied_ragdoll_01', price = 50, label = 'Ragdoll' },
			{ name = 'v_res_fa_book03', price = 50, label = 'boek kamasutra' },
			{ name = 'prop_weight_rack_02', price = 50, label = 'dumbbellrek' },
			{ name = 'prop_weight_bench_02', price = 50, label = 'Couchdrukset' },
			{ name = 'prop_tool_broom', price = 50, label = 'Broom' },
			{ name = 'prop_fire_exting_2a', price = 50, label = 'Fire extinguisher' },
			{ name = 'v_res_vacuum', price = 50, label = 'vacuum cleaner' },
			{ name = 'v_ret_gc_fan', price = 50, label = 'Fan' },
			{ name = 'prop_paint_stepl01b', price = 50, label = 'ladder' },
			{ name = 'bkr_prop_weed_bucket_01b', price = 50, label = 'Fertilizer' },
			{ name = 'v_club_vusnaketank', price = 50, label = 'terrarium' },
			{ name = 'prop_pooltable_02', price = 50, label = 'poolTable' },
			{ name = 'prop_pool_rack_02', price = 50, label = 'poolcues' },
			{ name = 'v_club_vu_deckcase', price = 50, label = 'dj set' },
			{ name = 'v_corp_servercln', price = 50, label = 'serverrack' }
		},
	},
	{
		categoryName = 'Random 2',
		items = {
			{ name = 'prop_dummy_01', price = 50, label = 'Dummy' },
			{ name = 'prop_egg_clock_01', price = 50, label = 'Egg Clock' },
			{ name = 'prop_el_guitar_01', price = 50, label = 'E Guitar 1' },
			{ name = 'prop_el_guitar_02', price = 50, label = 'E Guitar 2' },
			{ name = 'prop_el_guitar_03', price = 50, label = 'E Guitar 2' },
			{ name = 'prop_feed_sack_01', price = 50, label = 'Feed Sack' },
			{ name = 'prop_floor_duster_01', price = 50, label = 'Floor Duster' },
			{ name = 'prop_fruit_basket', price = 50, label = 'Fruit Basket' },
			{ name = 'prop_f_duster_02', price = 50, label = 'Duster' },
			{ name = 'prop_grapes_02', price = 50, label = 'Grapes' },
			{ name = 'prop_hotel_clock_01', price = 50, label = 'Hotel Clock' },
			{ name = 'prop_idol_case_01', price = 50, label = 'Idol Case' },
			{ name = 'prop_jewel_02a', price = 50, label = 'Jewels' },
			{ name = 'prop_jewel_02b', price = 50, label = 'Jewels' },
			{ name = 'prop_jewel_02c', price = 50, label = 'Jewels' },
			{ name = 'prop_jewel_03a', price = 50, label = 'Jewels' },
			{ name = 'prop_jewel_03b', price = 50, label = 'Jewels' },
			{ name = 'prop_jewel_04a', price = 50, label = 'Jewels' },
			{ name = 'prop_jewel_04b', price = 50, label = 'Jewels' },
			{ name = 'prop_j_disptray_01', price = 50, label = 'Display Tray' },
			{ name = 'prop_j_disptray_01b', price = 50, label = 'Display Tray' },
			{ name = 'prop_j_disptray_02', price = 50, label = 'Display Tray' },
			{ name = 'prop_j_disptray_03', price = 50, label = 'Display Tray' },
			{ name = 'prop_j_disptray_04', price = 50, label = 'Display Tray' },
			{ name = 'prop_j_disptray_04b', price = 50, label = 'Display Tray' },
			{ name = 'prop_j_disptray_05', price = 50, label = 'Display Tray' },
			{ name = 'prop_j_disptray_05b', price = 50, label = 'Display Tray' },
			{ name = 'prop_ld_greenscreen_01', price = 50, label = 'Green Screen' },
			{ name = 'prop_ld_handbag', price = 50, label = 'Handbag' },
			{ name = 'prop_ld_jerrycan_01', price = 50, label = 'Jerry Can' },
			{ name = 'prop_ld_keypad_01', price = 50, label = 'Keypad 1' },
			{ name = 'prop_ld_keypad_01b', price = 50, label = 'Keypad 2' },
			{ name = 'prop_ld_suitcase_01', price = 50, label = 'Suitcase 1' },
			{ name = 'prop_ld_suitcase_02', price = 50, label = 'Suitcase 2' },
			{ name = 'hei_p_attache_case_shut', price = 50, label = 'Suitcase 3' },
			{ name = 'prop_mr_rasberryclean', price = 50, label = 'Rasberry Clean' },
			{ name = 'prop_paper_bag_01', price = 50, label = 'Paper Bag' },
			{ name = 'prop_shopping_bags01', price = 50, label = 'Shopping Bags' },
			{ name = 'prop_shopping_bags02', price = 50, label = 'Shopping Bags 2' },
			{ name = 'prop_yoga_mat_01', price = 50, label = 'Yoga Mat 1' },
			{ name = 'prop_yoga_mat_02', price = 50, label = 'Yoga Mat 2' },
			{ name = 'prop_yoga_mat_03', price = 50, label = 'Yoga Mat 3' },
			{ name = 'p_ld_sax', price = 50, label = 'Sax' },
			{ name = 'p_ld_soc_ball_01', price = 50, label = 'SOCCER Ball' },
			{ name = 'p_watch_01', price = 50, label = 'Watch 1' },
			{ name = 'p_watch_02', price = 50, label = 'Watch 2' },
			{ name = 'p_watch_03', price = 50, label = 'Watch 3' },
			{ name = 'p_watch_04', price = 50, label = 'Watch 4' },
			{ name = 'p_watch_05', price = 50, label = 'Watch 5' },
			{ name = 'p_watch_06', price = 50, label = 'Watch 6' },
			{ name = 'apa_mp_h_acc_candles_01', price = 50, label = 'candle' },
			{ name = 'apa_mp_h_acc_candles_02', price = 50, label = 'candle 2' },
			{ name = 'apa_mp_h_acc_candles_04', price = 50, label = 'candle 3' },
			{ name = 'apa_mp_h_acc_candles_06', price = 50, label = 'candle 4' },
			{ name = 'apa_mp_h_acc_fruitbowl_02', price = 50, label = 'fruit bowl' },
			{ name = 'apa_mp_h_acc_tray_01', price = 50, label = 'thingies' },
			{ name = 'prop_bskball_01', price = 50, label = 'Basketball' },
			{ name = 'prop_cs_wrench', price = 50, label = 'Wrench' },
			{ name = 'prop_cs_bowie_knife', price = 50, label = 'Bowie Knife' },
			{ name = 'prop_w_me_hatchet', price = 50, label = 'Hatchet' }
		},
	},
	{
		categoryName = 'Details',
		items = {
			{ name = 'v_res_r_figcat', price = 50, label = 'Fig Cat' },
			{ name = 'v_res_r_figclown', price = 50, label = 'Fig Clown' },
			{ name = 'v_res_r_figauth2', price = 50, label = 'Fig Auth' },
			{ name = 'v_res_r_figfemale', price = 50, label = 'Fig Female' },
			{ name = 'v_res_r_figflamenco', price = 50, label = 'Fig Flamenco' },
			{ name = 'v_res_r_figgirl', price = 50, label = 'Fig Girl' },
			{ name = 'v_res_r_figgirlclown', price = 50, label = 'Fig Girl Clown' },
			{ name = 'v_res_r_figoblisk', price = 50, label = 'Fig Oblisk' },
			{ name = 'v_res_r_figpillar', price = 50, label = 'Fig Pillar' },
			{ name = 'v_res_r_teapot', price = 50, label = 'Teapot' },
			{ name = 'v_res_sculpt_dec', price = 50, label = 'Sculpture 1' },
			{ name = 'v_res_sculpt_decd', price = 50, label = 'Sculpture 2' },
			{ name = 'v_res_sculpt_dece', price = 50, label = 'Sculpture 3' },
			{ name = 'v_res_sculpt_decf', price = 50, label = 'Sculpture 4' },
			{ name = 'v_res_skateboard', price = 50, label = 'Skateboard' },
			{ name = 'v_res_sketchpad', price = 50, label = 'Sketchpad' },
			{ name = 'v_res_tissues', price = 50, label = 'Tissues' },
			{ name = 'v_res_tre_basketmess', price = 50, label = 'Basket' },
			{ name = 'v_res_tre_bin', price = 50, label = 'Bin' },
			{ name = 'v_res_tre_cushiona', price = 50, label = 'Cushion 1' },
			{ name = 'v_res_tre_cushionb', price = 50, label = 'Cushion 2' },
			{ name = 'v_res_tre_cushionc', price = 50, label = 'Cushion 3' },
			{ name = 'v_res_tre_cushiond', price = 50, label = 'Cushion 4' },
			{ name = 'v_res_tre_cushnscuzb', price = 50, label = 'Cushion 5' },
			{ name = 'v_res_tre_cushnscuzd', price = 50, label = 'Cushion 6' },
			{ name = 'v_res_tre_fruitbowl', price = 50, label = 'Fruitbowl' },
			{ name = 'v_med_p_sideboard', price = 50, label = 'Sideboard' },
			{ name = 'prop_idol_01', price = 50, label = 'Idol 1' },
			{ name = 'v_res_r_fighorsestnd', price = 50, label = 'Figurine black horse' },
			{ name = 'v_res_r_fighorse', price = 50, label = 'Figurine big horse' },
			{ name = 'v_res_r_figdancer', price = 50, label = 'Figurine dancer' },
			{ name = 'v_res_fa_idol02', price = 50, label = 'olifanten Figurine' },
			{ name = 'v_res_m_statue', price = 50, label = 'Sculpture' },
			{ name = 'v_med_p_vaseround', price = 50, label = 'Fase round' },
			{ name = 'ex_mp_h_acc_vase_05', price = 50, label = 'Fase Violet' },
			{ name = 'apa_mp_h_acc_dec_head_01', price = 50, label = 'Art work' },
			{ name = 'apa_mp_h_acc_dec_sculpt_02', price = 50, label = 'Art work 2' },
			{ name = 'ex_mp_h_acc_dec_plate_02', price = 50, label = 'Art work 3' },
			{ name = 'apa_mp_h_acc_bowl_ceramic_01', price = 50, label = 'schaal' },
			{ name = 'apa_mp_h_acc_dec_plate_01', price = 50, label = 'Scale 2' },
			{ name = 'apa_mp_h_acc_vase_01', price = 50, label = 'vase black and white' },
			{ name = 'apa_mp_h_acc_vase_02', price = 50, label = 'vase red' },
			{ name = 'apa_mp_h_acc_vase_05', price = 50, label = 'vase' },
			{ name = 'apa_mp_h_acc_vase_06', price = 50, label = 'vase black and white 2' }
		},
	},
	{
		categoryName = 'Storage',
		items = {
			{ name = 'v_res_cabinet', price = 50, label = 'Cabinet Large' },
			{ name = 'v_res_d_dressingtable', price = 50, label = 'Dressing Table' },
			{ name = 'v_res_d_sideunit', price = 50, label = 'Side Unit' },
			{ name = 'v_res_fh_sidebrddine', price = 50, label = 'Side Unit' },
			{ name = 'v_res_fh_sidebrdlngb', price = 50, label = 'Side Unit' },
			{ name = 'v_res_mbbedtable', price = 50, label = 'Bed Unit' },
			{ name = 'v_res_j_tvstand', price = 50, label = 'Tv Unit' },
			{ name = 'v_res_mbdresser', price = 50, label = 'Dresser Unit' },
			{ name = 'v_res_mbottoman', price = 50, label = 'Bottoman Unit' },
			{ name = 'v_res_mconsolemod', price = 50, label = 'Console Unit' },
			{ name = 'v_res_mcupboard', price = 50, label = 'Cupboard Unit' },
			{ name = 'v_res_mdchest', price = 50, label = 'Chest Unit' },
			{ name = 'v_res_msoncabinet', price = 50, label = 'Mason Unit' },
			{ name = 'v_res_m_armoire', price = 50, label = 'Armoire Unit' },
			{ name = 'v_res_m_sidetable', price = 50, label = 'Side Unit' },
			{ name = 'v_res_son_desk', price = 50, label = 'Desk Unit' },
			{ name = 'v_res_tre_bedsidetable', price = 50, label = 'Side Unit' },
			{ name = 'v_res_tre_bedsidetableb', price = 50, label = 'Side Unit 2' },
			{ name = 'v_res_tre_smallbookshelf', price = 50, label = 'Book Unit' },
			{ name = 'v_res_tre_storagebox', price = 50, label = 'Box Unit' },
			{ name = 'v_res_tre_storageunit', price = 50, label = 'Storage Unit' },
			{ name = 'v_res_tre_wardrobe', price = 50, label = 'Wardrobe Unit' },
			{ name = 'v_res_tre_wdunitscuz', price = 50, label = 'Wood Unit' },
			{ name = 'prop_devin_box_closed', price = 50, label = 'Bean Bag 1' },
			{ name = 'prop_mil_crate_01', price = 50, label = 'Mil Crate 1' },
			{ name = 'prop_mil_crate_02', price = 50, label = 'Mil Crate 2' },
			{ name = 'prop_ld_int_safe_01', price = 50, label = 'Safe' },
			{ name = 'v_corp_filecablow', price = 50, label = 'Filing cabinet Low' },
			{ name = 'v_corp_filecabtall', price = 50, label = 'Filing cabinet High' },
			{ name = 'apa_mp_h_str_shelffloorm_02', price = 50, label = 'Large modern cupboard' },
			{ name = 'v_ilev_frnkwarddr1', price = 50, label = 'Cupboard franklin' },
			{ name = 'prop_coathook_01', price = 50, label = 'Coat rack' },
			{ name = 'v_corp_lowcabdark01', price = 50, label = 'Filing cabinetLow black' },
			{ name = 'v_corp_tallcabdark01', price = 50, label = 'Filing cabinet High black' },
			{ name = 'v_corp_cabshelves01', price = 50, label = 'Filing cabinet black' },
			{ name = 'v_corp_offshelf', price = 50, label = 'Filing cabinet groot' },
			{ name = 'v_61_lng_mesh_unitc', price = 50, label = 'Bookcase white' },
			{ name = 'ba_wardrobe', price = 50, label = 'kledingkast' },
			{ name = 'apa_mp_h_str_sideboardl_06', price = 50, label = 'Cupboard  modern' },
			{ name = 'apa_mp_h_str_sideboardl_09', price = 50, label = 'Cupboard  modern 2' },
			{ name = 'apa_mp_h_str_shelfwallm_01', price = 50, label = 'Bookcase 2' },
			{ name = 'apa_mp_h_str_sideboardl_11', price = 50, label = 'Cupboard  modern 3' },
			{ name = 'imp_prop_impexp_parts_rack_03a', price = 50, label = 'car parts' },
			{ name = 'imp_prop_impexp_parts_rack_04a', price = 50, label = 'car parts 2' },
			{ name = 'imp_prop_impexp_parts_rack_05a', price = 50, label = 'car parts 3' },
			{ name = 'apa_mp_h_bed_chestdrawer_02', price = 50, label = 'chest of drawers' },
			{ name = 'hei_heist_bed_chestdrawer_04', price = 50, label = 'chest of drawers 2' },
			{ name = 'prop_rub_cabinet', price = 50, label = 'rusted filing cabinet' },
			{ name = 'prop_tv_cabinet_03', price = 50, label = 'tv little cupboard' },
			{ name = 'prop_tv_cabinet_04', price = 50, label = 'tv little cupboard 2' },
			{ name = 'prop_tv_cabinet_05', price = 50, label = 'tv little cupboard 3' },
			{ name = 'apa_mp_h_str_shelffreel_01', price = 50, label = 'ikea closet' },
			{ name = 'apa_mp_h_str_sideboardl_13', price = 50, label = 'cabinet modern 4' },
			{ name = 'apa_mp_h_str_sideboardl_14', price = 50, label = 'cabinet modern 5' },
			{ name = 'apa_mp_h_str_sideboardm_02', price = 50, label = 'cabinet modern 6' },
			{ name = 'bkr_prop_biker_garage_locker_01', price = 50, label = 'Biker Locker' },
			{ name = 'gr_prop_gr_bench_04b', price = 50, label = 'Biker Bench' }
		},
	},
	{
		categoryName = 'Electronics',
		items = {
			{ name = 'prop_trailr_fridge', price = 50, label = 'Old Fridge' },
			{ name = 'v_res_fh_speaker', price = 50, label = 'Speaker' },
			{ name = 'v_res_fh_speakerdock', price = 50, label = 'Speaker Dock' },
			{ name = 'v_res_fh_bedsideclock', price = 50, label = 'Bedside Clock' },
			{ name = 'v_res_fa_phone', price = 50, label = 'Phone' },
			{ name = 'v_res_fh_towerfan', price = 50, label = 'Tower Fan' },
			{ name = 'v_res_fa_fan', price = 50, label = 'Fan' },
			{ name = 'v_res_lest_bigscreen', price = 50, label = 'Bigscreen' },
			{ name = 'v_res_lest_monitor', price = 50, label = 'Monitor' },
			{ name = 'v_res_tre_mixer', price = 50, label = 'Mixer' },
			{ name = 'prop_cs_cctv', price = 50, label = 'CCTV' },
			{ name = 'prop_ld_lap_top', price = 50, label = 'Laptop' },
			{ name = 'prop_ld_monitor_01', price = 50, label = 'Monitor' },
			{ name = 'prop_speaker_05', price = 50, label = 'mounted speaker' },
			{ name = 'prop_tv_flat_03b', price = 50, label = 'kleine flatscreen' },
			{ name = 'prop_laptop_01a', price = 50, label = 'Open laptop' },
			{ name = 'prop_tv_flat_michael', price = 50, label = 'flatscreen hanging ing' },
			{ name = 'prop_dyn_pc', price = 50, label = 'pc' },
			{ name = 'prop_keyboard_01b', price = 50, label = 'Keybord' },
			{ name = 'prop_mouse_01b', price = 50, label = 'Computer mouse' },
			{ name = 'v_ret_gc_phone', price = 50, label = 'office phone' },
			{ name = 'prop_tv_flat_01', price = 50, label = 'Big flatscreen' },
			{ name = 'prop_arcade_01', price = 50, label = 'arcade' },
			{ name = 'prop_console_01', price = 50, label = 'gameconsole' },
			{ name = 'v_res_tre_dvdplayer', price = 50, label = 'dvd Player' },
			{ name = 'prop_speaker_08', price = 50, label = 'wooden speaker' },
			{ name = 'prop_cctv_mon_02', price = 50, label = 'cctv monitor' },
			{ name = 'prop_tv_flat_02', price = 50, label = 'flatscreen Standing' },
			{ name = 'prop_cctv_cam_01a', price = 50, label = 'cctv 2' },
			{ name = 'prop_dest_cctv_02', price = 50, label = 'cctv monitor 2' },
			{ name = 'prop_cctv_cam_07a', price = 50, label = 'cctv 3' },
			{ name = 'apa_mp_h_str_avunits_04', price = 50, label = 'flatscreen meubel' },
			{ name = 'apa_mp_h_str_avunits_01', price = 50, label = 'flatscreen meubel 2' },
			{ name = 'v_club_vu_deckcase', price = 50, label = 'dj set' },
			{ name = 'v_corp_servercln', price = 50, label = 'serverrack' },
			{ name = 'apa_mp_h_str_avunitl_01_b', price = 50, label = 'flat screen furniture 3' },
			{ name = 'apa_mp_h_str_avunitl_04', price = 50, label = 'flat screen furniture 4' },
			{ name = 'apa_mp_h_str_avunitm_01', price = 50, label = 'flat screen furniture 5' },
			{ name = 'apa_mp_h_str_avunitm_03', price = 50, label = 'flat screen furniture 6' },
			{ name = 'apa_mp_h_str_avunits_04', price = 50, label = 'flat screen furniture 7' },
			{ name = 'v_res_printer', price = 50, label = 'printer' },
			{ name = 'apa_mp_h_acc_phone_01', price = 50, label = 'old fashioned telephone' },
			{ name = 'v_res_mousemat', price = 50, label = 'mouse pad' },
			{ name = 'v_res_pcheadset', price = 50, label = 'headset' },
			{ name = 'v_res_pcspeaker', price = 50, label = 'PC speaker' },
			{ name = 'ba_prop_battle_club_speaker_small', price = 50, label = 'small box' },
			{ name = 'ba_prop_battle_club_speaker_med', price = 50, label = 'box' },
			{ name = 'ba_prop_battle_club_speaker_large', price = 50, label = 'big box' },
			{ name = 'v_res_pcspeaker', price = 50, label = 'PC speaker' },
			{ name = 'v_res_pcwoofer', price = 50, label = 'PC subwoofer' },
			{ name = 'prop_controller_01', price = 50, label = 'Controller' },
			{ name = 'prop_cs_remote_01', price = 50, label = 'Remote control' },
			{ name = 'prop_portable_hifi_01', price = 50, label = 'Radio' },
			{ name = 'prop_dj_deck_02', price = 50, label = 'DJ table' },
			{ name = 'prop_speaker_01', price = 50, label = 'Speaker' }
		},
	},
	{
		categoryName = 'Lighting',
		items = {
			{ name = 'v_corp_cd_desklamp', price = 50, label = 'Desk Corp Lamp' },
			{ name = 'v_res_desklamp', price = 50, label = 'Desk Lamp' },
			{ name = 'v_res_d_lampa', price = 50, label = 'Lamp AA' },
			{ name = 'v_res_fa_lamp1on', price = 50, label = 'Lamp 1' },
			{ name = 'v_res_fh_floorlamp', price = 50, label = 'Floor Lamp' },
			{ name = 'v_res_fh_lampa_on', price = 50, label = 'Lamp 2' },
			{ name = 'v_res_j_tablelamp1', price = 50, label = 'Table Lamp' },
			{ name = 'v_res_j_tablelamp2', price = 50, label = 'Table Lamp 2' },
			{ name = 'v_res_mdbedlamp', price = 50, label = 'Bed Lamp' },
			{ name = 'v_res_mplanttongue', price = 50, label = 'Plant Tongue Lamp' },
			{ name = 'v_res_mtblelampmod', price = 50, label = 'Table Lamp 3' },
			{ name = 'v_res_m_lampstand', price = 50, label = 'Lamp Stand' },
			{ name = 'v_res_m_lampstand2', price = 50, label = 'Lamp Stand 2' },
			{ name = 'v_res_m_lamptbl', price = 50, label = 'Table Lamp 4' },
			{ name = 'v_res_tre_lightfan', price = 50, label = 'Light Fan' },
			{ name = 'v_res_tre_talllamp', price = 50, label = 'Tall Lamp' },
			{ name = 'v_ret_fh_walllighton', price = 50, label = 'Wall Light' },
			{ name = 'v_ret_gc_lamp', price = 50, label = 'GC Lamp' },
			{ name = 'prop_dummy_light', price = 50, label = 'Flickering Light' },
			{ name = 'prop_ld_cont_light_01', price = 50, label = 'Side Wall Light' },
			{ name = 'V_44_D_emis', price = 50, label = 'Test Light' },
			{ name = 'prop_wall_light_07a', price = 50, label = 'lantaarn' },
			{ name = 'prop_wall_light_01a', price = 50, label = 'Cheap lamp' },
			{ name = 'v_serv_tu_light2_', price = 50, label = 'industrieel licht' },
			{ name = 'v_serv_tu_light3_', price = 50, label = 'industrieel licht2' },
			{ name = 'ba_prop_battle_lights_ceiling_l_a', price = 50, label = 'hanging lamp' },
			{ name = 'v_med_p_floorlamp', price = 50, label = 'Big lamp' },
			{ name = 'v_club_vu_lamp', price = 50, label = 'Smal lamp' },
			{ name = 'ba_prop_battle_lights_wall_l_a', price = 50, label = 'Wall lamp' },
			{ name = 'ba_prop_battle_lights_ceiling_l_c', price = 50, label = 'hanging lamp 2' },
			{ name = 'ba_prop_battle_lights_ceiling_l_b', price = 50, label = 'kroonluchter 2' },
			{ name = 'ba_prop_battle_lights_wall_l_c', price = 50, label = 'Wall lamp 2' },
			{ name = 'ba_prop_battle_lights_wall_l_b', price = 50, label = 'Wall lamp 3' },
			{ name = 'hei_heist_lit_lightpendant_02', price = 50, label = 'hanging lamp 3' },
			{ name = 'prop_oldlight_01b', price = 50, label = 'wall lamp 4' },
			{ name = 'apa_mp_h_lit_floorlampnight_07', price = 50, label = 'blue lamp' },
			{ name = 'apa_mp_h_ceiling_light_01', price = 50, label = 'commercial' },
			{ name = 'apa_mp_h_ceiling_light_01_day', price = 50, label = 'commercial 2' },
			{ name = 'apa_mp_h_ceiling_light_02', price = 50, label = 'ceiling light' },
			{ name = 'apa_mp_h_ceiling_light_02_day', price = 50, label = 'ceiling light 2' },
			{ name = 'ba_prop_battle_lights_ceiling_l_d', price = 50, label = 'commercial 3' },
			{ name = 'ba_prop_battle_lights_ceiling_l_f', price = 50, label = 'ceiling light 3' },
			{ name = 'ba_prop_battle_lights_ceiling_l_e', price = 50, label = 'ceiling light 4' },
			{ name = 'apa_mp_h_floorlamp_a', price = 50, label = 'floor lamp' },
			{ name = 'apa_mp_h_floorlamp_b', price = 50, label = 'floor lamp 2' },
			{ name = 'apa_mp_h_floorlamp_c', price = 50, label = 'floor lamp 3' },
			{ name = 'apa_mp_h_floor_lamp_int_08', price = 50, label = 'floor lamp 4' },
			{ name = 'apa_mp_h_lampbulb_multiple_a', price = 50, label = 'ceiling light 5' },
			{ name = 'apa_mp_h_lit_floorlamp_02', price = 50, label = 'floor lamp 5' },
			{ name = 'apa_mp_h_lit_floorlampnight_14', price = 50, label = 'floor lamp 6' },
			{ name = 'apa_mp_h_lit_floorlamp_03', price = 50, label = 'floor lamp 7' },
			{ name = 'apa_mp_h_lit_floorlamp_06', price = 50, label = 'floor lamp 8' },
			{ name = 'apa_mp_h_lit_floorlamp_10', price = 50, label = 'floor lamp 9' },
			{ name = 'apa_mp_h_lit_floorlamp_13', price = 50, label = 'floor lamp 10' },
			{ name = 'apa_mp_h_lit_floorlamp_17', price = 50, label = 'floor lamp 11' },
			{ name = 'apa_mp_h_lit_lamptablenight_16', price = 50, label = 'night light' },
			{ name = 'apa_mp_h_lit_lamptablenight_24', price = 50, label = 'night light 2' },
			{ name = 'apa_mp_h_lit_lamptable_005', price = 50, label = 'night light 3' },
			{ name = 'apa_mp_h_lit_lamptable_04', price = 50, label = 'night light 4' },
			{ name = 'apa_mp_h_lit_lamptable_09', price = 50, label = 'night light 5' },
			{ name = 'apa_mp_h_lit_lamptable_14', price = 50, label = 'night light 6' },
			{ name = 'apa_mp_h_lit_lamptable_17', price = 50, label = 'night light 7' },
			{ name = 'apa_mp_h_yacht_table_lamp_01', price = 50, label = 'night light 8' }
		},
	},
	{
		categoryName = 'Tables',
		items = {
			{ name = 'v_res_d_coffeetable', price = 50, label = 'Coffee Table 1' },
			{ name = 'v_res_d_roundtable', price = 50, label = 'Round Table' },
			{ name = 'v_res_d_smallsidetable', price = 50, label = 'Small Side Table' },
			{ name = 'v_res_fh_coftablea', price = 50, label = 'Table A' },
			{ name = 'v_res_fh_coftableb', price = 50, label = 'Table B' },
			{ name = 'v_res_fh_coftbldisp', price = 50, label = 'Table C' },
			{ name = 'v_res_fh_diningtable', price = 50, label = 'Dining Table' },
			{ name = 'v_res_j_coffeetable', price = 50, label = 'Coffee Table 2' },
			{ name = 'v_res_j_lowtable', price = 50, label = 'Low Table' },
			{ name = 'v_res_mdbedtable', price = 50, label = 'Bed Table' },
			{ name = 'v_res_mddesk', price = 50, label = 'Desk' },
			{ name = 'v_res_msidetblemod', price = 50, label = 'Side Table' },
			{ name = 'v_res_m_console', price = 50, label = 'Console Table' },
			{ name = 'v_res_m_dinetble_replace', price = 50, label = 'Dining Table 2' },
			{ name = 'v_res_m_h_console', price = 50, label = 'Console H Table' },
			{ name = 'v_res_m_stool', price = 50, label = 'Stool?' },
			{ name = 'v_res_tre_sideboard', price = 50, label = 'Sideboard Table' },
			{ name = 'v_res_tre_table2', price = 50, label = 'Table 2' },
			{ name = 'v_res_tre_tvstand', price = 50, label = 'Tv Table' },
			{ name = 'v_res_tre_tvstand_tall', price = 50, label = 'Tv Table Tall' },
			{ name = 'v_med_p_coffeetable', price = 50, label = 'Med Coffee Table' },
			{ name = 'v_med_p_desk', price = 50, label = 'Med Desk' },
			{ name = 'prop_yacht_table_01', price = 50, label = 'Yacht Table 1' },
			{ name = 'prop_yacht_table_02', price = 50, label = 'Yacht Table 2' },
			{ name = 'prop_yacht_table_03', price = 50, label = 'Yacht Table 3' },
			{ name = 'v_ret_csr_table', price = 50, label = 'CSR Table' },
			{ name = 'v_res_mconsoletrad', price = 50, label = 'high side table' },
			{ name = 'v_ilev_liconftable_sml', price = 50, label = 'Office tabel' },
			{ name = 'v_ret_tablesml', price = 50, label = 'Side table  marillaux' },
			{ name = 'apa_mp_h_yacht_coffee_table_02', price = 50, label = 'koffie table Brown' },
			{ name = 'apa_mp_h_yacht_side_table_01', price = 50, label = 'Side table Brown' },
			{ name = 'apa_mp_h_yacht_side_table_02', price = 50, label = 'ronde Side table' },
			{ name = 'apa_mp_h_tab_sidelrg_04', price = 50, label = 'ronde Side table 2' },
			{ name = 'v_club_vu_table', price = 50, label = 'Coverd Table' },
			{ name = 'apa_mp_h_tab_sidelrg_07', price = 50, label = 'koffieTable glas' },
			{ name = 'bkr_prop_weed_table_01b', price = 50, label = 'clapTable' },
			{ name = 'ba_prop_int_trad_table', price = 50, label = 'Stand Table' },
			{ name = 'apa_mp_h_str_sideboards_02', price = 50, label = 'Side table glas' },
			{ name = 'apa_mp_h_yacht_coffee_table_01', price = 50, label = 'koffieTable modern' },
			{ name = 'apa_mp_h_din_table_04', price = 50, label = 'dinner Table glas' },
			{ name = 'xm_prop_base_staff_desk_01', price = 50, label = 'desk + setup' },
			{ name = 'apa_mp_h_tab_coffee_07', price = 50, label = 'triangular side table' },
			{ name = 'apa_mp_h_tab_coffee_08', price = 50, label = 'white side table' },
			{ name = 'apa_mp_h_tab_sidelrg_01', price = 50, label = 'glass side table' },
			{ name = 'apa_mp_h_tab_sidelrg_02', price = 50, label = 'glass side table 2' },
			{ name = 'apa_mp_h_tab_sidesml_01', price = 50, label = 'folding table' },
			{ name = 'ba_prop_int_edgy_table_01', price = 50, label = 'table marble' },
			{ name = 'ba_prop_int_edgy_table_02', price = 50, label = 'table marble high' },
			{ name = 'apa_mp_h_tab_sidelrg_01', price = 50, label = 'glass side table' },
			{ name = 'xm_prop_lab_desk_01', price = 50, label = 'lab table' }
		},
	},
	{
		categoryName = 'Plants',
		items = {
			{ name = 'prop_fib_plant_01', price = 50, label = 'Plant Fib' },
			{ name = 'v_corp_bombplant', price = 50, label = 'Plant Bomb' },
			{ name = 'v_res_mflowers', price = 50, label = 'Plant Flowers' },
			{ name = 'v_res_mvasechinese', price = 50, label = 'Plant Chinese' },
			{ name = 'v_res_m_bananaplant', price = 50, label = 'Plant Banana' },
			{ name = 'v_res_m_palmplant1', price = 50, label = 'Plant Palm' },
			{ name = 'v_res_m_palmstairs', price = 50, label = 'Plant Palm 2' },
			{ name = 'v_res_m_urn', price = 50, label = 'Plant Urn' },
			{ name = 'v_res_rubberplant', price = 50, label = 'Plant Rubber' },
			{ name = 'v_res_tre_plant', price = 50, label = 'Plant' },
			{ name = 'v_res_tre_tree', price = 50, label = 'Plant Tree' },
			{ name = 'v_med_p_planter', price = 50, label = 'Planter' },
			{ name = 'v_ret_flowers', price = 50, label = 'Flowers' },
			{ name = 'v_ret_j_flowerdisp', price = 50, label = 'Flowers 1' },
			{ name = 'v_ret_j_flowerdisp_white', price = 50, label = 'Flowers 2' },
			{ name = 'v_res_m_vasefresh', price = 50, label = 'FlowerFase' },
			{ name = 'v_res_rosevasedead', price = 50, label = 'Pink Fase 2' },
			{ name = 'v_res_exoticvase', price = 50, label = 'FlowerFase 2' },
			{ name = 'v_res_rosevase', price = 50, label = 'Pink Fase' },
			{ name = 'prop_pot_plant_6a', price = 50, label = 'Hanging ende plant' },
			{ name = 'prop_pot_plant_02a', price = 50, label = 'Flower pot' },
			{ name = 'apa_mp_h_acc_plant_palm_01', price = 50, label = 'palm plant' },
			{ name = 'prop_plant_interior_05a', price = 50, label = 'flower box' },
			{ name = 'prop_plant_int_01a', price = 50, label = 'plant' },
			{ name = 'prop_plant_int_01b', price = 50, label = 'plant 2' },
			{ name = 'prop_plant_int_02a', price = 50, label = 'plant 3' },
			{ name = 'prop_plant_int_02b', price = 50, label = 'plant 4' },
			{ name = 'prop_plant_int_03a', price = 50, label = 'plant 5' },
			{ name = 'prop_plant_int_03b', price = 50, label = 'plant 6' },
			{ name = 'prop_plant_int_03c', price = 50, label = 'plant 7' },
			{ name = 'prop_plant_int_04a', price = 50, label = 'plant 8' },
			{ name = 'prop_plant_int_04c', price = 50, label = 'plant 9' },
			{ name = 'prop_plant_int_05b', price = 50, label = 'flower box 2' },
			{ name = 'prop_pot_plant_01a', price = 50, label = 'plant pot 2' },
			{ name = 'prop_pot_plant_01b', price = 50, label = 'plant pot 3' },
			{ name = 'prop_pot_plant_01c', price = 50, label = 'plant pot 4' },
			{ name = 'prop_pot_plant_01d', price = 50, label = 'plant pot 5' },
			{ name = 'prop_pot_plant_01e', price = 50, label = 'plant pot 6' },
			{ name = 'prop_pot_plant_03b', price = 50, label = 'plant pot 7' },
			{ name = 'prop_pot_plant_05a', price = 50, label = 'plant pot 8' },
			{ name = 'prop_pot_plant_05b', price = 50, label = 'plant pot 9' },
			{ name = 'p_int_jewel_plant_01', price = 50, label = 'plant pot 10' },
			{ name = 'p_int_jewel_plant_02', price = 50, label = 'plant pot 11' },
			{ name = 'apa_mp_h_acc_vase_flowers_01', price = 50, label = 'plant pot 12' },
			{ name = 'apa_mp_h_acc_vase_flowers_02', price = 50, label = 'plant pot 13' },
			{ name = 'apa_mp_h_acc_vase_flowers_03', price = 50, label = 'plant pot 14' },
			{ name = 'apa_mp_h_acc_vase_flowers_04', price = 50, label = 'plant pot 15' }
		},
	},
	{
		categoryName = 'Kitchen',
		items = {
			{ name = 'prop_washer_01', price = 50, label = 'Washer 1' },
			{ name = 'prop_washer_02', price = 50, label = 'Washer 2' },
			{ name = 'prop_washer_03', price = 50, label = 'Washer 3' },
			{ name = 'prop_washing_basket_01', price = 50, label = 'Washing Basket' },
			{ name = 'v_res_fridgemoda', price = 50, label = 'Fridge 1' },
			{ name = 'v_res_fridgemodsml', price = 50, label = 'Fridge 2' },
			{ name = 'prop_fridge_01', price = 50, label = 'Fridge 3' },
			{ name = 'prop_fridge_03', price = 50, label = 'Fridge 4' },
			{ name = 'prop_cooker_03', price = 50, label = 'Cooker' },
			{ name = 'prop_micro_01', price = 50, label = 'Microwave 1' },
			{ name = 'prop_micro_02', price = 50, label = 'Microwave 2' },
			{ name = 'prop_wok', price = 50, label = 'Wok' },
			{ name = 'v_res_cakedome', price = 50, label = 'Cake Plate' },
			{ name = 'v_res_fa_chopbrd', price = 50, label = 'Chopping Board' },
			{ name = 'v_res_mutensils', price = 50, label = 'Utensils' },
			{ name = 'v_res_pestle', price = 50, label = 'Pestle' },
			{ name = 'v_ret_ta_paproll', price = 50, label = 'PaperRoll 1' },
			{ name = 'v_ret_ta_paproll2', price = 50, label = 'PaperRoll 2' },
			{ name = 'v_ret_fh_pot01', price = 50, label = 'Pot 1' },
			{ name = 'v_ret_fh_pot02', price = 50, label = 'Pot 2' },
			{ name = 'v_ret_fh_pot05', price = 50, label = 'Pot 3' },
			{ name = 'prop_pot_03', price = 50, label = 'Pot 4' },
			{ name = 'prop_pot_04', price = 50, label = 'Pot 5' },
			{ name = 'prop_pot_05', price = 50, label = 'Pot 6' },
			{ name = 'prop_pot_06', price = 50, label = 'Pot 7' },
			{ name = 'prop_pot_rack', price = 50, label = 'Pot Rack' },
			{ name = 'prop_kitch_juicer', price = 50, label = 'Juicer' },
			{ name = 'v_res_ovenhobmod', price = 50, label = 'Stove' },
			{ name = 'v_res_mkniferack', price = 50, label = 'Knive' },
			{ name = 'v_res_mchopboard', price = 50, label = 'Cutting plank' },
			{ name = 'prop_cs_kitchen_cab_l', price = 50, label = 'Kitchen Cupboard Wide' },
			{ name = 'prop_cs_kitchen_cab_r', price = 50, label = 'Kitchen cupboard smal' },
			{ name = 'v_res_tre_fridge', price = 50, label = 'refrigerator' },
			{ name = 'apa_mp_h_acc_coffeemachine_01', price = 50, label = 'coffee machine' },
			{ name = 'p_new_j_counter_02', price = 50, label = 'Counter' },
			{ name = 'prop_bar_pump_09', price = 50, label = 'Pump 1' },
			{ name = 'prop_bar_pump_01', price = 50, label = 'Pump 2' },
			{ name = 'prop_chip_fryer', price = 50, label = 'Chips fryer' },
			{ name = 'prop_cleaver', price = 50, label = 'Knife' },
			{ name = 'prop_coffee_mac_02', price = 50, label = 'coffee machine' },
			{ name = 'prop_coffee_mac_01', price = 50, label = 'coffee machine 2' },
			{ name = 'prop_cs_fork', price = 50, label = 'Fork' },
			{ name = 'prop_cs_sink_filler', price = 50, label = 'Sink filler' },
			{ name = 'prop_toaster_01', price = 50, label = 'Toaster' },
			{ name = 'prop_cs_plate_01', price = 50, label = 'Plate' },
			{ name = 'prop_foodprocess_01', price = 50, label = 'Food Process' },
			{ name = 'prop_food_sugarjar', price = 50, label = 'Sugar Bowl' },
			{ name = 'prop_juice_dispenser', price = 50, label = 'Dispencer' },
			{ name = 'prop_knife_stand', price = 50, label = 'Knife holder' },
			{ name = 'prop_knife', price = 50, label = 'Knife 2' },
			{ name = 'prop_micro_04', price = 50, label = 'Microwave 4' },
			{ name = 'v_ret_fh_plate3', price = 50, label = 'Plate 5' },
			{ name = 'v_ilev_tt_plate01', price = 50, label = 'Plate 6' },
			{ name = 'v_res_fa_grater', price = 50, label = 'Grater' },
			{ name = 'v_res_tt_pizzaplate', price = 50, label = 'Pizza Plate' },
			{ name = 'v_ret_247_ketchup2', price = 50, label = 'Ketchup' }
		},
	},
	{
		categoryName = 'Bathroom',
		items = {
			{ name = 'prop_ld_toilet_01', price = 50, label = 'Toilet 1' },
			{ name = 'prop_toilet_01', price = 50, label = 'Toilet 2' },
			{ name = 'prop_toilet_02', price = 50, label = 'Toilet 3' },
			{ name = 'prop_sink_02', price = 50, label = 'Sink 1' },
			{ name = 'prop_sink_04', price = 50, label = 'Sink 2' },
			{ name = 'prop_sink_05', price = 50, label = 'Sink 3' },
			{ name = 'prop_sink_06', price = 50, label = 'Sink 4' },
			{ name = 'prop_soap_disp_01', price = 50, label = 'Soap Dispenser' },
			{ name = 'prop_shower_rack_01', price = 50, label = 'Shower Rack' },
			{ name = 'prop_handdry_01', price = 50, label = 'Hand Dryer 1' },
			{ name = 'prop_handdry_02', price = 50, label = 'Hand Dryer 2' },
			{ name = 'prop_towel_rail_01', price = 50, label = 'Towel Rail 1' },
			{ name = 'prop_towel_rail_02', price = 50, label = 'Towel Rail 2' },
			{ name = 'prop_towel_01', price = 50, label = 'Towel 1' },
			{ name = 'v_res_mbtowel', price = 50, label = 'Towel 2' },
			{ name = 'v_res_mbtowelfld', price = 50, label = 'Towel 3' },
			{ name = 'v_res_mbath', price = 50, label = 'Bath' },
			{ name = 'v_res_mbsink', price = 50, label = 'Sink' },
			{ name = 'v_ilev_mm_faucet', price = 50, label = 'tap' },
			{ name = 'v_res_tre_washbasket', price = 50, label = 'Washing mand' },
			{ name = 'prop_toilet_soap_02', price = 50, label = 'Tray Soap' },
			{ name = 'prop_bar_sink_01', price = 50, label = 'Sink' },
			{ name = 'apa_mp_h_bathtub_01', price = 50, label = 'Bath' },
			{ name = 'prop_toilet_brush_01', price = 50, label = 'Brush' },
			{ name = 'prop_toilet_roll_01', price = 50, label = 'Toilet rol' },
			{ name = 'prop_toilet_roll_02', price = 50, label = 'Toilet rol 2' },
			{ name = 'prop_toilet_shamp_01', price = 50, label = 'Shampoo' },
			{ name = 'prop_toilet_shamp_02', price = 50, label = 'Shampoo 2' }
		},
	},
	{
		categoryName = 'Medical',
		items = {
			{ name = 'v_med_barrel', price = 50, label = 'Barrel' },
			{ name = 'v_med_apecrate', price = 50, label = 'Ape Crate' },
			{ name = 'v_med_apecratelrg', price = 50, label = 'Ape Crate Large' },
			{ name = 'v_med_bed1', price = 50, label = 'Bed 1' },
			{ name = 'v_med_bed2', price = 50, label = 'Bed 2' },
			{ name = 'v_med_bedtable', price = 50, label = 'Bed Table' },
			{ name = 'v_med_bench1', price = 50, label = 'Bench 1' },
			{ name = 'v_med_bench2', price = 50, label = 'Bench 2' },
			{ name = 'v_med_benchcentr', price = 50, label = 'Bench Center' },
			{ name = 'v_med_benchset1', price = 50, label = 'Bench Set' },
			{ name = 'v_med_bigtable', price = 50, label = 'Big Table' },
			{ name = 'v_med_bin', price = 50, label = 'Bin' },
			{ name = 'v_med_centrifuge1', price = 50, label = 'Centrifuge' },
			{ name = 'v_med_cooler', price = 50, label = 'Cooler' },
			{ name = 'v_med_cor_ceilingmonitor', price = 50, label = 'Monitor' },
			{ name = 'v_med_cor_autopsytbl', price = 50, label = 'Autopsy Table' },
			{ name = 'v_med_cor_cembin', price = 50, label = 'Bin' },
			{ name = 'v_med_cor_cemtrolly2', price = 50, label = 'Trolley' },
			{ name = 'v_med_cor_chemical', price = 50, label = 'Chem' },
			{ name = 'v_med_cor_emblmtable', price = 50, label = 'BLM Table' },
			{ name = 'v_med_cor_fileboxa', price = 50, label = 'File Box' },
			{ name = 'v_med_cor_filingcab', price = 50, label = 'File Cab' },
			{ name = 'v_med_cor_hose', price = 50, label = 'Hose' },
			{ name = 'v_med_cor_largecupboard', price = 50, label = 'Large Cupboard' },
			{ name = 'v_med_cor_lightbox', price = 50, label = 'Lightbox' },
			{ name = 'v_med_cor_medstool', price = 50, label = 'Medstool' },
			{ name = 'v_med_cor_minifridge', price = 50, label = 'Minifridge' },
			{ name = 'v_med_cor_papertowels', price = 50, label = 'Papertowels' },
			{ name = 'v_med_cor_photocopy', price = 50, label = 'Photocopy' },
			{ name = 'v_med_cor_tvstand', price = 50, label = 'TV Stand' },
			{ name = 'v_med_cor_wallunita', price = 50, label = 'Wall Unit' },
			{ name = 'v_med_examlight', price = 50, label = 'Exam light' },
			{ name = 'v_med_gastank', price = 50, label = 'Gas Tank' },
			{ name = 'v_med_hazmatscan', price = 50, label = 'Hazmat Scan' },
			{ name = 'v_med_hospheadwall1', price = 50, label = 'Head Wall' },
			{ name = 'v_med_hospseating1', price = 50, label = 'Seating' },
			{ name = 'v_med_hosptable', price = 50, label = 'Hosp Table' },
			{ name = 'v_med_latexgloveboxblue', price = 50, label = 'Glove Box' },
			{ name = 'v_med_medwastebin', price = 50, label = 'Wastebin' },
			{ name = 'v_med_oscillator3', price = 50, label = 'Oscillator' },
			{ name = 'prop_ld_health_pack', price = 50, label = 'Health Pack' },
		},
	},
	{
		categoryName = 'Wall  Deco',
		items = {
			{ name = 'apa_p_h_acc_artwalll_02', price = 50, label = 'Painting whit marks' },
			{ name = 'v_ind_cs_toolboard', price = 50, label = 'Tools' },
			{ name = 'apa_mp_stilts_bed_art', price = 50, label = '3d art' },
			{ name = 'ex_office_swag_paintings03', price = 50, label = 'Paintingen Ground' },
			{ name = 'ex_mp_h_acc_artwallm_03', price = 50, label = 'abstract Painting' },
			{ name = 'ex_p_h_acc_artwallm_04', price = 50, label = 'abstract Painting 2' },
			{ name = 'ex_p_h_acc_artwalll_01', price = 50, label = 'abstract Painting Big' },
			{ name = 'apa_p_h_acc_artwalll_03', price = 50, label = 'abstract Painting 3' },
			{ name = 'ex_mp_h_acc_artwallm_02', price = 50, label = 'abstract Painting 4' },
			{ name = 'ex_p_h_acc_artwallm_03', price = 50, label = 'abstract Painting 5' },
			{ name = 'apa_mp_stilts_a_study_pics', price = 50, label = 'Paintingen' },
			{ name = 'apa_mp_h_acc_artwallm_02', price = 50, label = 'abstract Painting 6' },
			{ name = 'apa_mp_h_acc_artwalll_02', price = 50, label = 'abstract Painting 7' },
			{ name = 'apa_mp_h_acc_artwallm_04', price = 50, label = 'abstract Painting 8' },
			{ name = 'prop_dart_bd_cab_01', price = 50, label = 'Dartboard' },
			{ name = 'prop_dart_bd_01', price = 50, label = 'Dartboard 2' },
			{ name = 'hei_heist_acc_artwalll_01', price = 50, label = 'wall deco 1' },
			{ name = 'hei_heist_acc_artgolddisc_01', price = 50, label = 'wall deco 2' },
			{ name = 'hei_heist_acc_artgolddisc_02', price = 50, label = 'wall deco 3' },
			{ name = 'hei_heist_acc_artgolddisc_03', price = 50, label = 'wall deco 4' },
			{ name = 'hei_heist_acc_artgolddisc_04', price = 50, label = 'wall deco 5' },
			{ name = 'v_ilev_ra_doorsafe', price = 50, label = 'Luxury deco' }
		},
	},
	{
		categoryName = 'Useable',
		items = {
			{ name = 'gr_prop_gr_bench_04b', price = 15000, label = 'Basic Crafting Bench' },
			{ name = 'gr_prop_gr_bench_01b', price = 25000, label = 'Advanced Crafting Bench' },
			
		},
	},
}
